version: 0.2

run-as: root

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 13.10.1  
    commands:
      - echo Install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - npm install
      - cd frontend
      - npm install 
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - LICENSE
    - README.md
    - appspec.yml
    - scripts/*
    - package.json
    - node_modules/**/*
    - server.js
    - frontend/build/**/*
    - deploy.sh
